name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    branches: [ main ]

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true


jobs:
  lint:
    strategy:
      matrix:
        python-version: [ "3.9","3.10","3.11" ]
    runs-on: ubuntu-latest
    needs: [ changelog ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Lint
        run: |
          make install-lint
          make check-python

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@master

  shfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup shfmt
        uses: mfinelli/setup-shfmt@v3
      - name: Run shfmt
        run: shfmt -i 2 -d .

  changelog:
    runs-on: ubuntu-latest
    steps:
      # need to checkout otherwise paths-filter will fail on merge-queue trigger
      - uses: actions/checkout@v4
      - if: github.ref != 'refs/heads/main'
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            src:
              - 'unstructured_ingest/**'

      - if: steps.changes.outputs.src == 'true' && github.ref != 'refs/heads/main'
        uses: dangoslen/changelog-enforcer@v3


  setup:
    strategy:
      matrix:
        python-version: [ "3.9","3.10","3.11" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/base-cache
        with:
          python-version: ${{ matrix.python-version }}
          check-only: 'true'

  test_ingest_help:
    environment: ci
    strategy:
      matrix:
        python-version: [ "3.9","3.10","3.11" ]
    runs-on: ubuntu-latest
    needs: [ setup, lint ]
    steps:
      - uses: 'actions/checkout@v4'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Setup virtual environment
        uses: ./.github/actions/base-cache
        with:
          python-version: ${{ matrix.python-version }}
      - name: Validate --help
        run: |
          source .venv/bin/activate
          ./test_e2e/test-help.sh

  test_install_cli:
    environment: ci
    strategy:
      matrix:
        python-version: [ "3.9","3.10","3.11" ]
    runs-on: ubuntu-latest
    needs: [ setup, lint ]
    steps:
      - uses: 'actions/checkout@v4'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Validate --help
        run: |
          pip install .
          unstructured-ingest --help
