name: Parallel Connector Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:
    branches: [ main ]


jobs:
  s3:
    strategy:
      matrix:
        python-version: [ "3.9", "3.10" ]
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v4'
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test (end-to-end)
      run: |
        pip install -r ./requirements/local_partition/pdf.txt
        pip install -r ./requirements/connectors/s3.txt
        ./test_e2e/src/s3.sh

  local:
    strategy:
      matrix:
        python-version: [ "3.9", "3.10" ]
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test (end-to-end)
        run: |
          pip install -r ./requirements/local_partition/pdf.txt
          ./test_e2e/src/local.sh
          ./test_e2e/src/local-single-file.sh
          ./test_e2e/src/local-single-file-with-encoding.sh
          ./test_e2e/src/local-single-file-with-pdf-infer-table-structure.sh
          
